// Generated by gir (https://github.com/gtk-rs/gir @ 961febb2d103)
// from ../../gir-files (@ 95ca1c0a99e9)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GtkLayerShellEdge", sizeof(GtkLayerShellEdge), alignof(GtkLayerShellEdge));
    printf("%s;%zu;%zu\n", "GtkLayerShellKeyboardMode", sizeof(GtkLayerShellKeyboardMode), alignof(GtkLayerShellKeyboardMode));
    printf("%s;%zu;%zu\n", "GtkLayerShellLayer", sizeof(GtkLayerShellLayer), alignof(GtkLayerShellLayer));
    return 0;
}
