[options]
library = "GtkLayerShell"
version = "0.1"
target_path = "."
min_cfg_version = "0.1"
work_mode = "normal"
girs_directories = ["../gir-files", ".."]
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true

generate = [
    "GtkLayerShell.Edge",
    "GtkLayerShell.Layer",
    "GtkLayerShell.KeyboardMode",
    "GtkLayerShell.*",
]

manual = ["Gtk.Window", "Gdk.Monitor"]
