name: "Install_deps"
description: "Installs the dependencies, checks out the code and sets up caching"

runs:
  using: "composite"
  steps:
    - name: Update repos
      shell: bash
      run: sudo apt-get update
    - name: Install git and GTK3
      shell: bash
      run: sudo apt-get install -y git tar libgtk-3-dev libgtk-layer-shell-dev
    - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          gtk-layer-shell/target/
          gtk-layer-shell-sys/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
