name: "Install_deps"
description: "Installs the dependencies, checks out the code and sets up caching"

runs:
  using: "composite"
  steps:
    - name: Update repos
      shell: bash
      run: sudo apt-get update

    - name: Hold back grub-efi-amd64-signed # TODO: Remove temporary fix
      shell: bash
      run: sudo apt-mark hold grub-efi-amd64-signed
      
    - name: Upgrade system
      shell: bash
      run: sudo apt-get upgrade -y
    - name: Install git and GTK3
      shell: bash
      run: sudo apt-get install -y git tar libgtk-3-dev libgtk-layer-shell-dev
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          gtk-layer-shell/target/
          gtk-layer-shell-sys/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
