[options]
library = "GtkLayerShell"
version = "0.1"
target_path = "."
min_cfg_version = "0.1"
work_mode = "sys"
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "Gdk",
    "Gtk",
]