[options]
library = "GtkLayerShell"
version = "0.1"
target_path = "."
min_cfg_version = "0.1"
work_mode = "sys"
girs_directories = ["../gir-files"]
single_version_file = true

external_libraries = [
    "GLib",
    "Gdk",
    "Gtk",
]

[[object]]
name = "GtkLayerShell.*"
    [[object.function]]
    name = "get_zwlr_layer_surface_v1"
    ignore = true