name: "Build aarch64"

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-for-aarch64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            gtk-layer-shell/target/
            gtk-layer-shell-sys/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build in arm64 container
        uses: uraimo/run-on-arch-action@v2.2.1
        with:
          arch: aarch64
          distro: ubuntu_devel
          # Install deps into the container. With the token, the container will be cached
          # The image is cached publically like a package
          githubToken: ${{ github.token }}
          #  Install packages for the arm container (e.g. Dockerfile steps)
          install: |
            apt-get update -q -y
            apt-get upgrade -y
            apt-get install -q -y git tar rust-all libgtk-3-dev libgtk-layer-shell-dev
          #   .. run build steps on the container
          run: |
            cd gtk-layer-shell-sys
            cargo build --verbose --feature v0_6
            cargo test --verbose --feature v0_6
            cd ../gtk-layer-shell
            cargo build --verbose --feature v0_6
            cargo test --verbose --feature v0_6
            cargo build --example simple-example
