name: "Check major version"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/workflows/composite/install_deps/action.yml
      - name: Get the first character of the version of the gtk-layer-shell package to detect mayor version bumps
        id: major_version_check
        run: echo ::set-output name=MAJOR_VERSION::$(dpkg -s gtk-layer-shell | grep Version | sed 's/Version. //' | cut -c1-1)
      - name: Fail if mayor version was increased
        if: steps.major_version_check.outputs.MAJOR_VERSION != '7'
        run: exit 1
