name: Publish_wrapper

on:
  workflow_dispatch:
    inputs:
      wrapper_version:
        description: 'New version of the wrapper crate'     
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:devel
    steps:
      - name: Update system
        run: apt-get update -q -y && apt-get upgrade -y
      - name: Install git, GTK and Rust libraries
        run: apt-get install -y git tar rust-all libgtk-3-dev libgtk-layer-shell-dev
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            gtk-layer-shell/target/
            gtk-layer-shell-sys/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get the version number
        id: previous_version
        run: |
            echo ::set-output name=PREVIOUS_VERSION::$(grep -o -m 1 -P '(?<=version = ").*(?=")' ./gtk-layer-shell/Cargo.toml)
      - name: Output the version numbers
        run: |
            echo "Previous version: ${{ steps.previous_version.outputs.PREVIOUS_VERSION }}"
            echo "New version: ${{ github.event.inputs.wrapper_version }}"
      - name: Bump version number in Cargo.toml of the wrapper
        run: |
            sed -i '0,/version = "${{ steps.previous_version.outputs.PREVIOUS_VERSION }}"/{s//version = "${{ github.event.inputs.wrapper_version }}"/}' ./gtk-layer-shell/Cargo.toml
      - name: Bump version of badge in wrapper README.md
        run: |
            sed -i '0,/gtk-layer-shell\/${{ steps.previous_version.outputs.PREVIOUS_VERSION }}/{s//gtk-layer-shell\/${{ github.event.inputs.wrapper_version }}/}' ./gtk-layer-shell/README.md
            sed -i '0,/gtk-layer-shell\/${{ steps.previous_version.outputs.PREVIOUS_VERSION }}/{s//gtk-layer-shell\/${{ github.event.inputs.wrapper_version }}/}' ./gtk-layer-shell/README.md
      - name: Bump version of badge in repo README.md
        run: |
            sed -i '0,/gtk-layer-shell\/${{ steps.previous_version.outputs.PREVIOUS_VERSION }}/{s//gtk-layer-shell\/${{ github.event.inputs.wrapper_version }}/}' ./README.md
            sed -i '0,/gtk-layer-shell\/${{ steps.previous_version.outputs.PREVIOUS_VERSION }}/{s//gtk-layer-shell\/${{ github.event.inputs.wrapper_version }}/}' ./README.md
      - name: Workaround needed due to new git version
        run:  git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Commit the changes to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version number of wrapper crate and publish it
      - name: Publish on crates.io
        working-directory: ./gtk-layer-shell
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}