name: Security audit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
  push:
    paths:
      - '**/Cargo.toml'
  pull_request:
    branches:
      - main
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Delete directories not to be audited
      - run: rm -rf ./gir ./gir-files
      # Moves all files in sys dir to top-level dir
      - run: mv gtk-layer-shell/gtk-layer-shell-sys/* .
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # Moves all files in subfolder to top-level dir
      - run: mv gtk-layer-shell/* .
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}