name: "Update gir and all gir-files"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            components: rustfmt, clippy
      ## Update the gir submodule and install the new version
      - name: Install gir
        working-directory: ./gir
        run: |
          git pull
          ls
          export PATH=$PATH:/github/home/.cargo/bin
          cargo install --force --path .
      - uses: ./.github/actions/build_test_commit
        with:
          commit_message: Automatically updated the version of gir
      ## Update the gir files of the dependencies
      - name: Get newest gir-files from upstream
        working-directory: ./gir-files
        run: |
          git pull
      - uses: ./.github/actions/build_test_commit
        with:
          commit_message: Automatically updated the gir files
      ## Update the version of the gtk-layer-shell gir file
      ## Aborts if there was a major version bump
      - name: Get the first character of the version of the gtk-layer-shell package to detect mayor version bumps
        id: major_version_check
        run: |
          echo "MAJOR_VERSION=$(dpkg -s libgtk-layer-shell-dev | grep Version | sed 's/Version. 0.//' | cut -c1-1)" >> $GITHUB_OUTPUT
          echo "Version: ${{ steps.major_version_check.outputs.MAJOR_VERSION }}"
      - name: Fail if mayor version was increased
        if: steps.major_version_check.outputs.MAJOR_VERSION != '7'
        run: exit 1
      - name: Copy newest GtkLayerShell.gir file into the project folder
        run: |
          CWD_MY_VAR=$(pwd)
          cd /usr/share/gir-1.0
          for i in GtkLayerShell-*.*.gir; do cp "$i" $CWD_MY_VAR/"${i}"; done
      - uses: ./.github/actions/build_test_commit
        with:
          commit_message: Automatically updated the version of gtk-layer-shell
