name: "Update gir and all gir-files"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
            toolchain: nightly
            components: rustfmt, clippy
      ## Update the version of gir that is used for the code generation
      - name: Update gir submodule
        run: |
          git submodule update --remote
      - name: Install gir
        working-directory: ./gir
        run: |
          ls
          export PATH=$PATH:/github/home/.cargo/bin
          cargo install --force --path .
      - uses: ./.github/actions/build_test_commit
        with:
          commit_message: Automatically updated the version of gir
      ## Update the gir files of the dependencies
      - name: Get newest gir-files from upstream
        run: |
          mv ./gir-files/GtkLayerShell-0.1.gir ./GtkLayerShell-0.1.gir # Copy GtkLayerShell.gir file to root folder to save it from deletion
          rm -rf ./gir-files
          git clone --depth 1 https://github.com/gtk-rs/gir-files.git
          rm -rf ./gir-files/.github
          rm ./gir-files/.gitignore
          mv ./GtkLayerShell-0.1.gir ./gir-files/GtkLayerShell-0.1.gir # Put the GtkLayerShell.gir file back into the gir-files folder
      - uses: ./.github/actions/build_test_commit
        with:
          commit_message: Automatically updated the gir files
      ## Update the version of the gtk-layer-shell gir file
      ## Aborts if there was a major version bump
      - name: Get the first character of the version of the gtk-layer-shell package to detect mayor version bumps
        id: major_version_check
        run: |
          echo "MAJOR_VERSION=$(dpkg -s libgtk-layer-shell-dev | grep Version | sed 's/Version. 0.//' | cut -c1-1)" >> $GITHUB_OUTPUT
          echo "Version: ${{ steps.major_version_check.outputs.MAJOR_VERSION }}"
      - name: Fail if mayor version was increased
        if: steps.major_version_check.outputs.MAJOR_VERSION != '7'
        run: exit 1
      - name: Copy newest GtkLayerShell.gir file into gir-files folder
        run: |
          CWD_MY_VAR=$(pwd)
          cd /usr/share/gir-1.0
          for i in GtkLayerShell-*.*.gir; do cp "$i" $CWD_MY_VAR/gir-files/"${i}"; done
      - uses: ./.github/actions/build_test_commit
        with:
          commit_message: Automatically updated the version of gtk-layer-shell
